#!/usr/bin/env python3

import json
import sys
import subprocess

name = sys.argv[2]


def set_bw():
  with open(".env", "rt") as fp:
    lines = fp.readlines()
  
  item = {
    "secureNote": {"type": 0},
    "object": "item",
    "folderId": "03a62584-8162-4469-aa50-adb4010f822b",
    "type": 2,
    "name": name,
    "fields": []
  }
  
  for line in lines:
    key, val = line.strip().split("=", 1)
    item["fields"].append({"name": key, "value": val, "type": 0})
  
  
  line = json.dumps(item)
  res = subprocess.run(["bw", "encode"], input=line, text=True, capture_output=True)
  encoded = res.stdout
  res = subprocess.run(["bw", "create", "item"], input=encoded, text=True, capture_output=True)
  print(f"Created {name}")

def get_bw():
  res = subprocess.run(["bw", "get", "item", name], text=True, capture_output=True)
  item = json.loads(res.stdout)
  with open(".env", "wt") as fp:
    for field in item["fields"]:
      fp.write(f"{field['name']}={field['value']}\n")
  print(f"Loaded {name}")

if sys.argv[1] == "get":
  get_bw()

if sys.argv[1] == "set":
  set_bw()
