version: "3.7"

services:
  server:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "config:/mosquitto/config"
      - "log:/mosquitto/log"
      - "data:/mosquitto/data"
    ports:
      - "1883:1883/tcp"
      - "8883:8883/tcp"
    networks:
      public:
        ipv6_address: ${IPV6}
    logging:
        driver: "journald"
    healthcheck:
      test: ["CMD", "/usr/bin/mosquitto_pub", "-h", "localhost", "-p", "1883", "-t", "healthcheck", "-m", "ok"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  config:
  data:
  log:

networks:
  public:
    external:
      name: public
