version: "3.7"

services:
  server:
    image: gotify/server
    labels:
      - traefik.enable=true
      - traefik.http.routers.gotify.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.gotify.tls.certresolver=le
      - traefik.http.routers.gotify.entrypoints=websecure
      - traefik.http.services.gotify.loadbalancer.server.port=80
    environment:
      - GOTIFY_DEFAULTUSER_NAME=${DEFAULT_USERNAME}
      - GOTIFY_DEFAULTUSER_PASS=${DEFAULT_PASSWORD}
      - TZ="Europe/Copenhagen"
    volumes:
      - data:/app/data
    networks:
      traefik:
        ipv6_address: ${IPV6}


volumes:
  data:

networks:
  traefik:
    external:
      name: traefik_inside
