version: "3.7"

services:
  client:
    image: restic/restic
    environment:
      - RESTIC_PASSWORD
      - RESTIC_REPOSITORY
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - cache:/root/.cache
    logging:
      driver: journald

volumes:
  cache:

