#!/usr/bin/env sh

ACTION="$1"
shift

SERV="$1"
shift

VOL="$1"
shift

export SERVICE=${SERV}
export VOLUME=${SERV}_${VOL}
export HOSTNAME=$(hostname)


/usr/bin/docker-compose --file SERVICE_DIR/docker-compose.yml --project-directory SERVICE_DIR run --rm client ${ACTION} "$@"
